name: Code Checks

on:
  pull_request:
    branches:
      - main

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

#permissions:
#  contents: read

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pylint-odoo isort
 
      - name: Run flake8
        run: flake8 --config .flake8 ./openacademy ./mobilephones

      - name: Run pylint
        run: pylint --rcfile=.pylintrc --load-plugins=pylint_odoo --valid-odoo-versions=18.0 ./openacademy ./mobilephones

      - name: Run isort check
        run: isort --check-only --diff ./openacademy ./mobilephones

  build_and_tests:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    needs: linters
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker compose -f docker-compose.yaml build

      - name: Start Odoo service
        run: docker compose -f docker-compose.yaml up -d web

      - name: Wait for DB
        run: docker compose exec web bash -c "until pg_isready -h db -p 5432; do sleep 1; done"

      - name: Run Odoo tests
        run: |
          docker compose exec web \
            python3 odoo/odoo-bin \
              -d odoo_test \
              -i mobilephones,openacademy \
              --test-tags /mobilephones,/openacademy \
              --stop-after-init
